# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Luiz Gavioli
tagline:          'Just me'
description:      ''
url:              https://luizgavioli.com
baseurl:          /

author:
  name:           'Luiz Gavioli'
  url:            https://luizgavioli.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luizbag/luizbag.github.io
